#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const { spawnSync } = require("child_process");
const { loadManifest } = require("./verify-manifest.cjs");

const repoRoot = path.resolve(__dirname, "..");
const exampleDir = path.join(repoRoot, "example");
const isWin = process.platform === "win32";

function which(name) {
  const dir = process.env.TISH_BIN_DIR?.trim();
  if (dir) {
    const bin = path.join(dir, isWin ? `${name}.exe` : name);
    if (fs.existsSync(bin)) return bin;
  }
  try {
    const out = spawnSync(isWin ? "where" : "which", [name], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    if (out.status !== 0 || !out.stdout) return null;
    const line = out.stdout
      .trim()
      .split(/[\r\n]+/)
      .map((s) => s.trim())
      .find(Boolean);
    return line || null;
  } catch {
    return null;
  }
}

function writeToolchainLock(tish, tishFmt, tishLint) {
  const pkg = JSON.parse(fs.readFileSync(path.join(repoRoot, "package.json"), "utf8"));
  const lines = [
    `# Generated by npm run example:verify — do not hand-edit`,
    `generatedAt: ${new Date().toISOString()}`,
    `extensionVersion: ${pkg.version}`,
    `tishLsp.releaseTag (package.json): ${pkg.tishLsp?.releaseTag ?? "(none)"}`,
    ``,
    `tish: ${tish ?? "(not found)"}`,
    `tish-fmt: ${tishFmt ?? "(not found)"}`,
    `tish-lint: ${tishLint ?? "(not found)"}`,
    ``,
  ];
  if (tish) {
    const v = spawnSync(tish, ["--version"], { encoding: "utf8" });
    lines.push(`tish --version:\n${(v.stdout || v.stderr || "").trim()}`);
  }
  fs.writeFileSync(path.join(exampleDir, "toolchain-lock.txt"), lines.join("\n") + "\n", "utf8");
}

function expectFmt(tishFmt, absPath, expect) {
  const r = spawnSync(tishFmt, ["--check", absPath], { encoding: "utf8" });
  const ok = r.status === 0;
  if (expect === "pass" && !ok) {
    console.error(`tish-fmt --check expected pass for ${absPath}:\n${r.stderr || r.stdout}`);
    return false;
  }
  if (expect === "fail" && ok) {
    console.error(`tish-fmt --check expected fail (non-zero) for ${absPath}`);
    return false;
  }
  return true;
}

function expectLint(tishLint, absPath, lint) {
  const r = spawnSync(tishLint, [absPath], { encoding: "utf8" });
  const out = `${r.stdout || ""}${r.stderr || ""}`;
  if (r.status !== lint.expectExit) {
    console.error(`tish-lint expected exit ${lint.expectExit} for ${absPath}, got ${r.status}\n${out}`);
    return false;
  }
  for (const sub of lint.stdoutContains || []) {
    if (!out.includes(sub)) {
      console.error(`tish-lint output for ${absPath} missing substring: ${sub}\n${out}`);
      return false;
    }
  }
  return true;
}

function expectRun(tish, absPath, expectExit) {
  const r = spawnSync(tish, ["run", absPath], {
    encoding: "utf8",
    cwd: path.dirname(absPath),
  });
  if (r.status !== expectExit) {
    console.error(
      `tish run expected exit ${expectExit} for ${absPath}, got ${r.status}\n${r.stderr || r.stdout}`
    );
    return false;
  }
  return true;
}

function main() {
  const manifest = loadManifest(repoRoot);
  const tish = which("tish");
  const tishFmt = which("tish-fmt");
  const tishLint = which("tish-lint");
  if (!tish || !tishFmt || !tishLint) {
    console.error(
      "example:verify requires tish, tish-fmt, and tish-lint on PATH (or set TISH_BIN_DIR to a directory containing them)."
    );
    console.error({ tish, tishFmt, tishLint });
    process.exit(1);
  }

  writeToolchainLock(tish, tishFmt, tishLint);

  const results = [];
  for (const f of manifest.fixtures) {
    const abs = path.join(exampleDir, f.path);
    if (!fs.existsSync(abs)) {
      console.error(`Missing fixture file: ${abs}`);
      results.push(false);
      continue;
    }
    if (f.fmtCheck) {
      results.push(expectFmt(tishFmt, abs, f.fmtCheck.expect));
    }
    if (f.lint) {
      results.push(expectLint(tishLint, abs, f.lint));
    }
    if (f.run) {
      results.push(expectRun(tish, abs, f.run.expectExit));
    }
  }

  if (process.env.EXAMPLE_VERIFY_BUILD === "1") {
    const outDir = path.join(repoRoot, "tish_out");
    const valid = path.join(exampleDir, "fixtures", "valid.tish");
    const r = spawnSync(tish, ["build", valid, "--output", outDir, "--target", "native"], {
      encoding: "utf8",
      cwd: repoRoot,
    });
    if (r.status !== 0) {
      console.error(`tish build failed:\n${r.stderr || r.stdout}`);
      results.push(false);
    } else {
      results.push(true);
    }
  }

  if (results.some((x) => !x)) {
    process.exit(1);
  }
  console.log("example:verify OK");
}

main();
